// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urdspbrqexbsecgmuiee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZHNwYnJxZXhic2VjZ211aWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzIyOTAsImV4cCI6MjA2MjA0ODI5MH0.m2KWfngwYLCgL-3N0UMZf7ql2AHLmFF2aIPAjuhx9ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);